require("dotenv").config();

import * as grpc from "@grpc/grpc-js";

import { StreamAggregatesSpotExchangeRateServiceV1Client } from "@kaiko-sdk/node/sdk/sdk_grpc_pb";
import { StreamAggregatesSpotExchangeRateResponseV1 } from "@kaiko-sdk/node/sdk/stream/aggregates_spot_exchange_rate_v1/response_pb";
import { StreamAggregatesSpotExchangeRateRequestV1 } from "@kaiko-sdk/node/sdk/stream/aggregates_spot_exchange_rate_v1/request_pb";

import * as v8 from "v8";
import * as fs from "fs";

function createHeapSnapshot() {
  const snapshotStream = v8.getHeapSnapshot();
  // It's important that the filename end with `.heapsnapshot`,
  // otherwise Chrome DevTools won't open it.
  const fileName = `heapsnapshots/${Date.now()}.heapsnapshot`;
  const fileStream = fs.createWriteStream(fileName);
  snapshotStream.pipe(fileStream);
}

function healthCheck() {
  setInterval(() => {
    console.log("checking health....");
    createHeapSnapshot();
  }, 60000);
}

const main = () => {
  // Setup authentication
  const token = process.env.KAIKO_API_KEY || "1234"; // Put your api key here

  const metaCallback = (
    _params: unknown,
    callback: (err: Error | null, metadata?: grpc.Metadata) => void
  ) => {
    const meta = new grpc.Metadata();
    meta.add("Authorization", `Bearer ${token}`);
    callback(null, meta);
  };

  const channelCreds = grpc.credentials.createSsl() as any;
  const callCreds = grpc.credentials.createFromMetadataGenerator(metaCallback);
  const creds = grpc.credentials.combineCallCredentials(
    channelCreds,
    callCreds
  );

  aggregatesRequest(creds);
  healthCheck();
};

const aggregatesRequest = (creds: grpc.CallCredentials): void => {
  const client = new StreamAggregatesSpotExchangeRateServiceV1Client(
    "gateway-v0-grpc.kaiko.ovh:443",
    creds as any
  );
  const request = new StreamAggregatesSpotExchangeRateRequestV1();

  const pairs = getPairs().map((pair) => pair.toLowerCase());

  pairs.forEach((pair: string) => {
    request.setSources(true);
    request.setAggregate("1m");
    request.setCode(pair);

    const call = client.subscribe(request);

    call.on("data", (response: StreamAggregatesSpotExchangeRateResponseV1) => {
      // console.log(`code: ${response.getCode()}, price: ${response.getPrice()}`);
      // response.getSourcesMap().forEach(source => console.log(source.getDataList().map(s => s.getExchangeCode())));
      // console.log(response.getSourcesMap)
      // response
      //   .getSourcesMap()
      //   .forEach((s, key) => console.log(key, s.getPrice()));
      // console.log("----");
      // console.log('LOAD AVG:', os.loadavg(), 'FREE MEM:', (os.freemem()));
    });

    call.on("end", () => {
      console.log("Stream ended", pair);
    });

    call.on("error", (error: grpc.ServiceError) => {
      if (error.code === grpc.status.CANCELLED) {
        return;
      }
      // console.error(error);
      return;
    });
  });
};

function getPairs() {
  return [
    "BTC-USD",
    "ETH-USD",
    "BNB-USD",
    "BTC-JPY",
    "BTC-EUR",
    "ADA-USD",
    "XRP-USD",
    "DOT-USD",
    "ETH-BTC",
    "BUSD-USD",
    "UNI-USD",
    "LINK-USD",
    "EOS-USD",
    "ETH-EUR",
    "TRX-USD",
    "IOST-USD",
    "XLM-USD",
    "DOGE-USD",
    "BNB-BTC",
    "ADA-BTC",
    "ATOM-USD",
    "XRP-BTC",
    "LTC-USD",
    "HT-USD",
    "BTC-GBP",
    "USDT-USD",
    "LTC-BTC",
    "ZEC-USD",
    "ETC-USD",
    "NEO-USD",
    "SRM-USD",
    "BSV-USD",
    "USDC-USD",
    "ETH-JPY",
    "DASH-USD",
    "SOL-USD",
    "XEM-BTC",
    "ONT-USD",
    "DOT-BTC",
    "SUSHI-USD",
    "BTT-USD",
    "IOST-BTC",
    "VET-USD",
    "BCH-BTC",
    "ADA-KRW",
    "SXP-USD",
    "KSM-USD",
    "LINK-BTC",
    "XEM-USD",
    "ZRX-USD",
    "AAVE-USD",
    "BCH-USD",
    "RVN-USD",
    "CRV-USD",
    "BNB-EUR",
    "ALGO-USD",
    "QTUM-USD",
    "MIOTA-USD",
    "XRP-EUR",
    "XTZ-USD",
    "OMG-USD",
    "ADA-EUR",
    "RVN-BTC",
    "ATOM-BTC",
    "XMR-USD",
    "YFI-USD",
    "DOT-KRW",
    "ICX-USD",
    "AVAX-USD",
    "FIL-USD",
    "BAND-USD",
    "EOS-BTC",
    "SOL-BTC",
    "XLM-BTC",
    "ZIL-USD",
    "XMR-BTC",
    "BTC-AUD",
    "XRP-TRY",
    "EGLD-USD",
    "JST-USD",
    "THETA-USD",
    "MATIC-USD",
    "SNX-USD",
    "XEM-KRW",
    "GRT-BTC",
    "DOT-EUR",
    "GRT-EUR",
    "DOGE-BTC",
    "SRM-BTC",
    "LUNA-BTC",
    "FTM-BTC",
    "BSV-BTC",
    "LINK-EUR",
    "CRO-KRW",
    "DAI-USD",
    "NPXS-USD",
    "DASH-BTC",
    "XLM-EUR",
    "CRO-USD",
    "PAY-USD",
    "BNB-ETH",
    "COMP-USD",
    "XEM-JPY",
    "TRX-BTC",
    "IOST-KRW",
    "RSR-USD",
    "REN-USD",
    "AAVE-BTC",
    "NEO-BTC",
    "BAT-USD",
    "HT-BTC",
    "UNI-BTC",
    "YFII-USD",
    "HOT-USD",
    "ADA-ETH",
    "SRM-KRW",
    "NU-USD",
    "BTT-KRW",
    "FTT-BTC",
    "BSV-KRW",
    "VET-BTC",
    "ALGO-BTC",
    "WAVES-USD",
    "ZEC-BTC",
    "ZRX-BTC",
    "FTT-USD",
    "CRO-BTC",
    "MIOTA-BTC",
    "BNT-USD",
    "ETH-AUD",
    "XLM-JPY",
    "TOMO-USD",
    "BCH-EUR",
    "SXP-BTC",
    "LINK-ETH",
    "BTG-KRW",
    "NANO-USD",
    "RUNE-USD",
    "FRONT-USD",
    "ETC-BTC",
    "ATOM-KRW",
    "HBAR-USD",
    "SUSHI-BTC",
    "KSM-BTC",
    "BTC-PLN",
    "ZIL-BTC",
    "ZRX-KRW",
    "MKR-USD",
    "XTZ-BTC",
    "LRC-USD",
    "OXT-USD",
    "BORA-KRW",
    "ZEN-USD",
    "BNT-BTC",
    "YFI-BTC",
    "MATIC-BTC",
    "VGX-BTC",
    "ICX-BTC",
    "SUN-USD",
    "EGLD-BTC",
    "MANA-USD",
    "BAL-USD",
    "ETC-KRW",
    "NEO-TRY",
    "OMG-BTC",
    "USDC-GBP",
    "OCEAN-USD",
    "SNT-KRW",
    "DASH-TRY",
    "CAKE-BNB",
    "UNI-KRW",
    "CHZ-USD",
    "XEM-ETH",
    "BNB-TRY",
    "KAVA-USD",
    "MFT-KRW",
    "REN-BTC",
    "EOS-ETH",
    "BAT-BTC",
    "XLM-TRY",
    "ONT-BTC",
    "LINK-GBP",
    "QTUM-KRW",
    "XTZ-KRW",
    "ENJ-USD",
    "XRP-ETH",
    "CVC-USD",
    "EPT-KRW",
    "ZB-QC",
    "WAXP-KRW",
    "EOS-EUR",
    "TUSD-USD",
    "NPXS-ETH",
    "BAND-BTC",
    "PAX-USD",
    "ATOM-TRY",
    "LTC-GBP",
    "MED-KRW",
    "COMP-BTC",
    "STORJ-USD",
    "WAVES-BTC",
    "AAVE-EUR",
    "SNX-BTC",
    "CARRY-KRW",
    "THETA-BTC",
    "HBAR-BTC",
    "ALGO-EUR",
    "OMG-KRW",
    "XTZ-EUR",
    "LSK-BTC",
    "LTC-ETH",
    "XVS-BTC",
    "NANO-BTC",
    "QTUM-BTC",
    "DGB-BTC",
    "BCH-JPY",
    "HBAR-KRW",
    "DGB-USD",
    "GRT-GBP",
    "DOT-BNB",
    "ZIL-KRW",
    "HT-ETH",
    "KNC-USD",
    "ENJ-BTC",
    "AKRO-USD",
    "ANKR-KRW",
    "GT-USD",
    "CHSB-BTC",
    "AVAX-BTC",
    "LSK-USD",
    "UMA-USD",
    "EOS-TRY",
    "VET-KRW",
    "ICX-KRW",
    "MKR-BTC",
    "ZRX-EUR",
    "TOMO-BTC",
    "NMR-USD",
    "XRP-GBP",
    "TFUEL-KRW",
    "CRV-BTC",
    "MLK-KRW",
    "BTS-USD",
    "TRX-ETH",
    "XVS-BNB",
    "GAS-KRW",
    "FIL-BTC",
    "FET-USD",
    "RUNE-BTC",
    "ANKR-BTC",
    "RSR-BTC",
    "SC-BTC",
    "PAXG-USD",
    "COTI-BTC",
    "MBL-KRW",
    "XTZ-TRY",
    "ONE-USD",
    "RFR-KRW",
    "ANT-USD",
    "ETH-RUB",
    "XRP-AUD",
    "DOGE-EUR",
    "SOL-ETH",
    "SC-USD",
    "USDC-EUR",
    "OMG-EUR",
    "LUNA-BNB",
    "STX-USD",
    "DKA-KRW",
    "DENT-USD",
    "DCR-BTC",
    "BNB-AUD",
    "KNC-BTC",
    "SOL-BNB",
    "MANA-BTC",
    "NU-EUR",
    "ENJ-KRW",
    "THETA-KRW",
    "XVG-BTC",
    "STEEM-KRW",
    "KCS-USD",
    "PAXG-BTC",
    "HOT-BNB",
    "DCR-USD",
    "ARK-KRW",
    "DASH-ETH",
    "STMX-KRW",
    "CELO-USD",
    "SAND-BTC",
    "KEY-USD",
    "ELF-BTC",
    "REP-BTC",
    "TFUEL-BTC",
    "FTM-BNB",
    "LRC-BTC",
    "GAS-BTC",
    "ORN-BTC",
    "ETH-PLN",
    "RLC-USD",
    "AION-USD",
    "VET-ETH",
    "PIXEL-KRW",
    "IQ-KRW",
    "CRO-HT",
    "USDC-AUD",
    "ETC-EUR",
    "ONT-KRW",
    "IOST-ETH",
    "LOOM-KRW",
    "XLM-ETH",
    "LTC-JPY",
    "XTZ-GBP",
    "GLM-KRW",
    "STX-BTC",
    "ONE-BTC",
    "PNT-USD",
    "MANA-KRW",
    "OGN-USD",
    "REP-USD",
    "FET-BTC",
    "FIL-EUR",
    "LOOM-BTC",
    "MTL-KRW",
    "ELF-USD",
    "ZEN-BTC",
    "PAY-BTC",
    "HOT-ETH",
    "ELF-KRW",
    "NU-BTC",
    "ONGAS-USD",
    "MARO-KRW",
    "QKC-KRW",
    "CELO-BTC",
    "DOT-ETH",
    "KNC-KRW",
    "GRT-USD",
    "ALGO-GBP",
    "FSN-USD",
    "XMR-EUR",
    "NMR-BTC",
    "AVAX-ETH",
    "LEO-USD",
    "GRS-KRW",
    "UTK-USD",
    "VTHO-USD",
    "DENT-ETH",
    "ZEC-ETH",
    "BAL-BTC",
    "GHST-ETH",
    "ALPHA-BTC",
    "WRX-USD",
    "ETH-MXN",
    "ORBS-KRW",
    "SRM-BNB",
    "DASH-EUR",
    "AERGO-KRW",
    "EGLD-BNB",
    "JST-KRW",
    "CHZ-BTC",
    "TMTG-KRW",
    "OCEAN-BTC",
    "BNB-BIDR",
    "SOLVE-KRW",
    "KMD-KRW",
    "NEAR-BTC",
    "ARK-BTC",
    "SNT-USD",
    "MIOTA-KRW",
    "POWR-KRW",
    "KSM-EUR",
    "UNFI-BTC",
    "REP-KRW",
    "REQ-BTC",
    "SXP-BNB",
    "DIA-BTC",
    "TON-KRW",
    "QTUM-QC",
    "SC-KRW",
    "NEO-ETH",
    "STRAX-KRW",
    "XEM-QC",
    "WAVES-KRW",
    "BTS-QC",
    "UNI-ETH",
    "KMD-BTC",
    "LSK-KRW",
    "KAVA-BTC",
    "ONGAS-KRW",
    "CELR-BTC",
    "WNXM-USD",
    "AAVE-ETH",
    "IRIS-BTC",
    "CHSB-ETH",
    "BTM-BTC",
    "MOC-KRW",
    "POLY-KRW",
    "BTG-BTC",
    "ATOM-BNB",
    "ZRX-ETH",
    "WIN-USD",
    "ONT-ETH",
    "BTG-USD",
    "OMG-ETH",
    "LAMB-USD",
    "DMT-KRW",
    "LUNA-KRW",
    "STORJ-KRW",
    "UNI-BNB",
    "YFI-EUR",
    "CVC-BTC",
    "RVN-BNB",
    "YFII-BTC",
    "NU-GBP",
    "SNX-GBP",
    "ARDR-KRW",
    "TRB-BTC",
    "INJ-BTC",
    "KMD-USD",
    "SKL-BTC",
    "SCRT-BTC",
    "IGNIS-KRW",
    "STORJ-BTC",
    "ZEC-EUR",
    "AAVE-GBP",
    "WAVES-EUR",
    "ABBC-USD",
    "CTXC-USD",
    "WTC-USD",
    "CVC-KRW",
    "AION-BTC",
    "JST-BTC",
    "ADX-BTC",
    "KAVA-KRW",
    "SNT-BTC",
    "HNT-USD",
    "PIVX-BTC",
    "SNX-EUR",
    "BTT-BTC",
    "ZB-USD",
    "ATOM-ETH",
    "BNT-EUR",
    "EMC2-KRW",
    "ANT-BTC",
    "HIVE-KRW",
    "BCH-ETH",
    "SXP-EUR",
    "DNT-BTC",
    "GRT-ETH",
    "UMA-BTC",
    "STMX-BTC",
    "BTS-BTC",
    "NEXO-USD",
    "MIOTA-ETH",
    "PNT-BTC",
    "DVP-KRW",
    "BZRX-BTC",
    "LRC-ETH",
    "SBD-KRW",
    "GLM-BTC",
    "CEL-USD",
    "ONGAS-BTC",
    "UTK-BTC",
    "POWR-BTC",
    "XMR-ETH",
    "STEEM-BTC",
    "FSN-BTC",
    "NEXO-BTC",
    "HIVE-USD",
    "BNT-GBP",
    "LUNA-HT",
    "ZIL-ETH",
    "CTSI-BTC",
    "AMPL-USD",
    "OGN-BTC",
    "LSK-PLN",
    "DUSK-USD",
    "DOGE-ETH",
    "QTUM-EUR",
    "KCS-BTC",
    "BAT-ETH",
    "KSM-BNB",
    "ROSE-BTC",
    "ADX-KRW",
    "GAS-ETH",
    "UMB-USD",
    "UMB-ETH",
    "UMB-BTC",
    "ZDEX-USD",
    "ZDEX-EUR",
    "FTS-USD",
    "INT-USD",
  ];
}

main();
